site_name: Laser cutter manual

repo_url: https://github.com/uppsala-makerspace/laser_cutter
edit_uri: blob/main/docs/

nav:
  - Home: index.md
  - Procedure:
    - Overview: steps/overview.md
    - Start ventilation: start_ventilation.md
    - Get material: get_material.md
    - Setup laser: setup_laser.md
    - Position material: position_material.md
    - Setup LaserCut: setup_lasercut.md
    - Start laser: start_laser.md
  - Lessons:
    - 1. Laser safety: lessons/1_laser_safety.md
    - 2. Fire safety: lessons/2_fire_safety.md
    - 3. Your first cut: lessons/3_your_first_cut.md
  - Misc:
    - Code of conduct: CODE_OF_CONDUCT.md
    - Contributing: CONTRIBUTING.md
    - Contributors: contributors.md
    - License: LICENSE.md
    - Troubleshooting: troubleshooting/README.md

theme:
  name: material
  greetings: Welcome to the laser cutter manual
  font:
    text: Lato
    code: JetBrains Mono
  palette:
    primary: black

  logo: logo/2024_logo_Simple_White_thumbnail.png

  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.footer
    - navigation.expand
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - content.action.view
    
markdown_extensions:
  - toc:
      toc_depth: 2
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - tables
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


