site_name: Laser cutter manual

repo_url: https://github.com/uppsala-makerspace/laser_cutter
edit_uri: blob/main/docs/

nav:
  - Home: index.md
  - Procedure:
    - Overview: steps/README.md
    - Get material: steps/get_material.md
    - Start ventilation: steps/start_ventilation.md
    - Power on the laser cutter: steps/power_on_laser_cutter.md
    - Start computer: steps/start_computer.md
    - Start LightBurn: steps/start_lightburn.md
    - Position material: steps/position_material.md
    - Setup laser physically: steps/setup_laser_physically.md
    - Setup laser in LightBurn: steps/setup_laser_in_lightburn.md
    - Load or create an image: load_image.md
    - Setup LightBurn: steps/setup_lightburn.md
    - Close enclosure: steps/close_enclosure.md
    - Start laser: steps/start_laser.md
    - Turn off laser: steps/turn_off_laser.md
    - Turn off computer: steps/turn_off_computer.md
    - Turn off ventilation: steps/turn_off_ventilation.md

  - Lessons:
    - Overview: lessons/README.md
    - 1. Turn on everything: lessons/1_turn_on_everything.md
    - 2. Be a good controller: lessons/2_be_a_good_controller.md
    - 1. Laser safety: lessons/11_laser_safety.md
    - 2. Fire safety: lessons/12_fire_safety.md
    - 3. Your first cut: lessons/23_your_first_cut.md
  - Misc:
    - Code of conduct: CODE_OF_CONDUCT.md
    - Contributing: CONTRIBUTING.md
    - Contributors: contributors.md
    - Frequently Asked Questions: faq.md
    - License: LICENSE.md
    - Troubleshooting: troubleshooting/README.md

theme:
  name: material
  greetings: Welcome to the laser cutter manual
  font:
    text: Lato
    code: JetBrains Mono
  palette:
    primary: black

  logo: logo/2024_logo_Simple_White_thumbnail.png

  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.footer
    - navigation.expand
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - content.action.view
    
markdown_extensions:
  - toc:
      toc_depth: 2
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - tables
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


